package ZombiesOntologia;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Mon Dec 14 17:19:14 CET 2020 by gonvega
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Abominacion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ABOMINACION.<p>
     * 
     */
    public static final OWLClass CLASS_ABOMINACION = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Abominacion"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Arma
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARMA.<p>
     * 
     */
    public static final OWLClass CLASS_ARMA = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Arma"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Calle
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CALLE.<p>
     * 
     */
    public static final OWLClass CLASS_CALLE = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Calle"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Carta
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CARTA.<p>
     * 
     */
    public static final OWLClass CLASS_CARTA = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Carta"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Casilla
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CASILLA.<p>
     * 
     */
    public static final OWLClass CLASS_CASILLA = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Casilla"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Conexion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONEXION.<p>
     * 
     */
    public static final OWLClass CLASS_CONEXION = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Conexion"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Corredor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CORREDOR.<p>
     * 
     */
    public static final OWLClass CLASS_CORREDOR = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Corredor"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Exit
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EXIT.<p>
     * 
     */
    public static final OWLClass CLASS_EXIT = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Exit"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Gordo
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GORDO.<p>
     * 
     */
    public static final OWLClass CLASS_GORDO = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Gordo"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Indoor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INDOOR.<p>
     * 
     */
    public static final OWLClass CLASS_INDOOR = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Indoor"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Noise
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NOISE.<p>
     * 
     */
    public static final OWLClass CLASS_NOISE = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Noise"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Normal
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NORMAL.<p>
     * 
     */
    public static final OWLClass CLASS_NORMAL = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Normal"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Objetivo
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OBJETIVO.<p>
     * 
     */
    public static final OWLClass CLASS_OBJETIVO = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Objetivo"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Objeto
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OBJETO.<p>
     * 
     */
    public static final OWLClass CLASS_OBJETO = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Objeto"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Sangre
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SANGRE.<p>
     * 
     */
    public static final OWLClass CLASS_SANGRE = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Sangre"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Skills
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SKILLS.<p>
     * 
     */
    public static final OWLClass CLASS_SKILLS = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Skills"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Survivor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SURVIVOR.<p>
     * 
     */
    public static final OWLClass CLASS_SURVIVOR = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Survivor"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Token
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TOKEN.<p>
     * 
     */
    public static final OWLClass CLASS_TOKEN = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Token"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#Zombie
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ZOMBIE.<p>
     * 
     */
    public static final OWLClass CLASS_ZOMBIE = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Zombie"));

    /* ***************************************************
     * Class http://www.owl-ontologies.com/Ontology1607619237.owl#ZombieSource
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ZOMBIESOURCE.<p>
     * 
     */
    public static final OWLClass CLASS_ZOMBIESOURCE = factory.getOWLClass(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#ZombieSource"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/Ontology1607619237.owl#AtToken
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ATTOKEN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ATTOKEN = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#AtToken"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/Ontology1607619237.owl#ConectTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONECTTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONECTTO = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#ConectTo"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/Ontology1607619237.owl#Habilidad
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HABILIDAD.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HABILIDAD = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Habilidad"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/Ontology1607619237.owl#Lugar
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property LUGAR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LUGAR = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Lugar"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/Ontology1607619237.owl#Mano
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MANO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MANO = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Mano"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/Ontology1607619237.owl#Mochila
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MOCHILA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MOCHILA = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Mochila"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/Ontology1607619237.owl#NumeroPersonajes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property NUMEROPERSONAJES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_NUMEROPERSONAJES = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#NumeroPersonajes"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/Ontology1607619237.owl#Punto1
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PUNTO1.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PUNTO1 = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Punto1"));

    /* ***************************************************
     * Object Property http://www.owl-ontologies.com/Ontology1607619237.owl#Punto2
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PUNTO2.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PUNTO2 = factory.getOWLObjectProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Punto2"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#AbrePuerta
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ABREPUERTA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ABREPUERTA = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#AbrePuerta"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#Alcantarilla
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ALCANTARILLA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ALCANTARILLA = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Alcantarilla"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#Dados
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DADOS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DADOS = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Dados"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#Daño
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DAÑO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DAÑO = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Daño"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#Distancia
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DISTANCIA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DISTANCIA = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Distancia"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#Experiencia
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property EXPERIENCIA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_EXPERIENCIA = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Experiencia"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#MaxAccionesTurno
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property MAXACCIONESTURNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_MAXACCIONESTURNO = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#MaxAccionesTurno"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#Name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NAME = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Name"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#NumeroMin
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NUMEROMIN.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NUMEROMIN = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#NumeroMin"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#Posx
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property POSX.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_POSX = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Posx"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#Posy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property POSY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_POSY = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Posy"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#Prioridad
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PRIORIDAD.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PRIORIDAD = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Prioridad"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#Puerta
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PUERTA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PUERTA = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Puerta"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#PuntosExperiencia
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PUNTOSEXPERIENCIA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PUNTOSEXPERIENCIA = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#PuntosExperiencia"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#Ruido
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property RUIDO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_RUIDO = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Ruido"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#Vida
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VIDA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VIDA = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#Vida"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#god_Class29
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property GOD_CLASS29.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_GOD_CLASS29 = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#god_Class29"));

    /* ***************************************************
     * Data Property http://www.owl-ontologies.com/Ontology1607619237.owl#god_Class31
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property GOD_CLASS31.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_GOD_CLASS31 = factory.getOWLDataProperty(IRI.create("http://www.owl-ontologies.com/Ontology1607619237.owl#god_Class31"));


}
