package ZombiesOntologia.impl;

import ZombiesOntologia.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultConexion <br>
 * @version generated on Mon Dec 14 17:19:14 CET 2020 by gonvega
 */
public class DefaultConexion extends WrappedIndividualImpl implements Conexion {

    public DefaultConexion(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
